sonar.projectKey=statisticsnorway_ssb-sgis
sonar.organization=statisticsnorway
sonar.host.url=https://sonarcloud.io

sonar.sources=src/ssb_sgis2/
sonar.tests=tests/

sonar.python.version=3.13
sonar.python.coverage.reportPaths=coverage.xml

sonar.sourceEncoding=UTF-8
